#!/usr/bin/env python3
"""
Shared configuration for documentation archival
Maintains canonical list of files to archive across scripts
"""

# Canonical list of files to archive (old status reports and summaries)
FILES_TO_ARCHIVE = [
    "HACKATHON_DEMO_SYNC_COMPLETE.md",
    "ENHANCED_INSIGHTS_UPDATE_SUMMARY.md", 
    "HACKATHON_UPDATES_SUMMARY.md",
    "DEMO_INSIGHTS_IMPROVEMENTS.md",
    "DASHBOARD_UPGRADE_COMPLETE.md",
    "NOVA_STRANDS_UPDATE_SUMMARY.md",
    "HACKATHON_CREDIBILITY_UPDATE_SUMMARY.md",
    "HACKATHON_CROSS_PLATFORM_SYNC_COMPLETE.md",
    "DEMO_DASHBOARD_IMPROVEMENT_PLAN.md",
    "DEMO_FILES_UPDATE_SUMMARY.md",
    "ENHANCED_DASHBOARD_COMPLETE.md",
    "AUTOSCROLL_IMPROVEMENTS_REPORT.md",
    "CREDIBILITY_FIXES.md",
    "CREDIBILITY_FIXES_APPLIED.md",
    "CROSS_PLATFORM_COMPATIBILITY_UPDATE.md",
    "DASHBOARD_COMPARISON.md",
    "DASHBOARD_FEATURE_ANALYSIS.md",
    "DEMO_AUTOMATION_SUMMARY.md",
    "DEMO_VISUALS_GUIDE.md",
    "HACKATHON_VIDEO_COMPLETE.md",
    "HACKATHON_VIDEO_SCRIPT.md",
    "VIDEO_DEMO_VISUALS.md"
]